# Projet numérique : câbles sous-marins

Corentin Hennion, Léa Mailhol 

## Questions théoiques



$\underline{Question~1~:} $
La loi forte des grands nombres nous autorise à estimer l'espérence conditionnelle par la moyenne empirique des simulations conditionnelles. 

$ \underline{Question~2~:}$
On note $\textbf{Z} = \begin{pmatrix} Z(x_{1})=z(x_{1}) \\ ...\\...\\ Z(x_{N})=z(x_{N}) \end{pmatrix} $ le vecteur correspond aux variables aléatoires liées aux points de discrétisation sans observation et $\textbf{W} = \begin{pmatrix} Z(x_{j_1}) \\ ...\\...\\ Z(x_{j_n})\end{pmatrix} $ le vecteur correspondant aux variables aléatoires liées aux points d'observation. 

On cherche la loi de la variable aléatoire $Z|W = w$ où w est le vecteurs des valeurs prises aux points d'observations.

On utilise la résulats du chapitre Probabilité 4 car les vecteurs $\textbf{Z}$ et $\textbf{W}$ sont des vecteurs gaussiens à densité.

On obtient que la foncton de densité de la variable $Z|W = w$ est : 

$$f_{Z|W = w}(x) = \frac{1}{(2\pi)^{(N+1)/2}\sqrt{det(C)}}exp(-\frac{1}{2}(x-m_{Z|W=w})^t C^{-1}(x-m_{Z|W=w}))$$


Avec $ m_{Z|W=w} = \mu - C_{Z,W}C_W^{-1}(w-\mu) $ et $ C = \Sigma - C_{Z,W}C_w^{-1}C_{W,Z}$

La matrice $C_{W,Z}$ a pour coefficients les $C_{W,Z}[i,k] = \sigma_{ij_k} = |x_i - x_{j_k}|$

Donc $Z|W = w$ est un vecteur gaussien à densité d'espérence $ m_{Z|W=w}$ et de matrice de convariance $C$

$ \underline{Question~3~: }$ On prend $Y=(Y_1, ..., ..., Y_p)$ un vecteur de composantes gaussiennes indépendantes d'espérance nulle et de variance 1.

Prenons $Z = m + RY$ avec $m$ vecteur de taille $p$ et $R$ une matrice de taille $p x p$. $Z$ est un vecteur gaussien par combinaison linéaire de vecteurs gaussiens.

Alors chaque composante du vecteur $Z$ a pour espérance $E(Z_i) = m_i + E(\sum_{j=0}^p R_{i,j}\times Y_i) = m_i +\sum_{j=0}^p R_{i,j}  E(Y_{j}) = m_{i}$

Sa matrice de covariance est la matrice $C$ telle que $C_{i,j} = Cov(Z_i, Z_j) = E((Z_i - m_i)(Z_j - m_j)) = E(Z_iZ_j) - m^2 = \sum_{k=0}^p\sum_{l=0}^p r_{ik}r_{jl} E(Y_kY_l)$

Or $E(Y_kY_l) = 0$ si $k\ne l $ car les variables aléatoires sont indépendantes donc $C_{i,j} = \sum_{k=0}^p r_{ik}r_{jk}$

Au final, $Z$ est un vecteur gaussien d'espérance $m$ et de matrice de covariance est $C=RR^t$ 

$\underline{ Question~4~:}$ L'algorithme de simulation conditionnelle va se dérouler comme suit :

On cherche $P_Z$ et on utilise la formule des probabilités totales : $P_Z = \sum_{w} P_{Z|W = w}P(W = w)$ avec Z et W définis en question 2.

On connait les $P(W = w)$ et il nous faut calculer $P_{Z|W = w}$. Comme python ne peut simuler que des variables aléatoires gaussiennes d'espérance nulle et de variance 1, on doit se ramener à $Y_w$ qui est tel que $(Z|W = w) = (m + RY_w) $

Pour cela on calcule $m$ avec l'expression donnée à la question 2 : $m = m_{Z|W=w}$
Et pour $R$ on utilise la résolution python de la factorisation de Cholesky qui est définie par $C=RR^t$ avec $C$ la matrice de la question 2. 

On peut donc simuler la variable $Z|W = w$ en passant par $Y$ est on obtient finalement une simulation de $P_Z$.

## Implementation 

In [1]:
#Chargement de dépendances
import numpy as np
import matplotlib.pyplot as plt
#Discrétisation
A=0
B=500
N=101 #Nombre de points de discrétisation
Delta = (B-A)/(N-1)
discretization_indexes = np.arange(N)
discretization = discretization_indexes*Delta
#Paramètres du modèle
mu=-5
a = 50
sigma2 = 12
#Données
observation_indexes = [0,20,40,60,80,100]
depth = np.array([0,-4,-12.8,-1,-6.5,0])
#Indices des composantes correspondant aux observations et aux componsantes non observées
18
unknown_indexes=list(set(discretization_indexes)-set(observation_indexes))

$ \underline{ Question~1~:}$

In [11]:
def cov(a , sigma2 , mat_dist) :
    if type(mat_dist) == float or int :
        return sigma2 * np.exp(-np.abs(mat_dist)/a)
    else :
        N , n = np.shape(mat_dist)
        matcov = np.empty((N , n))
        for i in range(N) :
            for j in range(n) :
                matcov[i, j] = sigma2 * np.exp(-np.abs(mat_dist[i, j])/a)
        return matcov   

$ \underline{ Question~2~:}$

In [22]:
#la matrice de distance est définie par mat_dist[i,k] = |x[i] - x[k]|
mat_dist = np.array( [[np.abs(discretization[i]-discretization[j]) for i in range (N)] for j in range(N)])

[[  0.   5.  10. ... 490. 495. 500.]
 [  5.   0.   5. ... 485. 490. 495.]
 [ 10.   5.   0. ... 480. 485. 490.]
 ...
 [490. 485. 480. ...   0.   5.  10.]
 [495. 490. 485. ...   5.   0.   5.]
 [500. 495. 490. ...  10.   5.   0.]]


$ \underline{ Question~3~:}$

In [23]:
matcov_Z = cov(a, sigma2, mat_dist)

$ \underline{ Question~4~:}$